export const EXAM_ATTEMPT_STATUS = {
  IN_PROGRESS: "IN_PROGRESS",
  SUBMITTED: "SUBMITTED",
  AUTO_SUBMITTED: "AUTO_SUBMITTED",
} as const;

export const EXAM_ATTEMPT_STATUSES = [
  EXAM_ATTEMPT_STATUS.IN_PROGRESS,
  EXAM_ATTEMPT_STATUS.SUBMITTED,
  EXAM_ATTEMPT_STATUS.AUTO_SUBMITTED,
] as const;

export const TERMINAL_EXAM_ATTEMPT_STATUSES = [
  EXAM_ATTEMPT_STATUS.SUBMITTED,
  EXAM_ATTEMPT_STATUS.AUTO_SUBMITTED,
] as const;

export const STUDENT_EXAM_STATE = {
  IN_PROGRESS: "IN_PROGRESS",
  NOT_STARTED: "NOT_STARTED",
  COMPLETED: "COMPLETED",
} as const;

export const STUDENT_EXAM_STATES = [
  STUDENT_EXAM_STATE.IN_PROGRESS,
  STUDENT_EXAM_STATE.NOT_STARTED,
  STUDENT_EXAM_STATE.COMPLETED,
] as const;

export const ESSAY_IMAGE_MAX_COUNT = 5;
export const ESSAY_IMAGE_MAX_BYTES = 10 * 1024 * 1024;
export const ESSAY_IMAGE_ALLOWED_FORMATS = [
  "jpg",
  "jpeg",
  "png",
  "webp",
] as const;
export const ESSAY_IMAGE_ALLOWED_MIME_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
] as const;
export const ESSAY_IMAGE_CLOUDINARY_FOLDER = "thpt-mock-test/essay-images";
export const ESSAY_IMAGE_UPLOAD_SIGNATURE_MAX_AGE_SECONDS = 600;
