export const EXAM_STRUCTURE_QUESTION_TYPE = {
  SINGLE_CHOICE: "SINGLE_CHOICE",
  TRUE_FALSE: "TRUE_FALSE",
  SHORT_ANSWER: "SHORT_ANSWER",
  ESSAY_IMAGE: "ESSAY_IMAGE",
} as const;

export const EXAM_STRUCTURE_QUESTION_TYPES = [
  EXAM_STRUCTURE_QUESTION_TYPE.SINGLE_CHOICE,
  EXAM_STRUCTURE_QUESTION_TYPE.TRUE_FALSE,
  EXAM_STRUCTURE_QUESTION_TYPE.SHORT_ANSWER,
  EXAM_STRUCTURE_QUESTION_TYPE.ESSAY_IMAGE,
] as const;

export const EXAM_STRUCTURE_TEMPLATE_NAME_MAX_LENGTH = 150;
export const EXAM_STRUCTURE_SECTION_TITLE_MAX_LENGTH = 150;
export const EXAM_STRUCTURE_ITEM_ID_MAX_LENGTH = 100;
export const EXAM_STRUCTURE_MAX_SECTIONS = 20;
export const EXAM_STRUCTURE_MAX_QUESTIONS_PER_SECTION = 100;
export const EXAM_STRUCTURE_MAX_TOTAL_QUESTIONS = 200;
export const EXAM_STRUCTURE_TOTAL_SCORE_HUNDREDTHS = 1000;

export const BUILT_IN_THPT_EXAM_STRUCTURE_TEMPLATE_NAME = "Chuẩn thi THPT";
